In [35]:
import pandas as pd

df = pd.read_csv('pokemon_data.csv')

#df = pd.read=[excel/]

#print(df.columns)
#print(df.Name)

#print(df[['Name','Type 1', 'HP']])

#print(df.iloc[1:4]) #read rows 1 to 4

#print(df.iloc[2,1])  #specific row and column

#for index, row in df.iterrows():
#    print(index, row)

#df.loc[df['Type 1']== "Fire"] # search for

#df.describe()

#df.sort_values('Name', ascending=False) #sort by name
#df.sort_values(['Type 1', 'HP'], ascending=[1,0]) # multiple sort

#df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def']+ df['Speed']

#df = df.drop(columns=['Total'])

#df['Total'] = df.iloc[:, 4:10].sum(axis=1) # another way to total

#cols = list(df.columns.values)   ##  move columns
#df = df[cols[0:4] + [cols[-1]] + cols[4:12]]

#df.to_csv('modified.csv', index=False)# write to a new csv
#df.to_excel ('modified.xlsx')

print (df.head(5))

   #                   Name Type 1  Type 2  Legendary  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison      False  45      49       49
1  2                Ivysaur  Grass  Poison      False  60      62       63
2  3               Venusaur  Grass  Poison      False  80      82       83
3  3  VenusaurMega Venusaur  Grass  Poison      False  80     100      123
4  4             Charmander   Fire     NaN      False  39      52       43

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
0       65       65     45           1      False
1       80       80     60           1      False
2      100      100     80           1      False
3      122      120     80           1      False
4       60       50     65           1      False

In [41]:

#filtering and saving to a new csv file with a reset index
#new_df = df.loc[(df['Type 1'] == 'Grass')  & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]
#new_df.to_csv('filtered.csv')
#new_df = new_df.reset_index()
 
#df.loc[df['Name'].str.contains('Mega')]
#df.loc[~df['Name'].str.contains('Mega')]  #does not contain Mega

,#,Name,Type 1,Type 2,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,False,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,False,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,False,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,False,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,False,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,True,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,True,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,True,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,True,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,True,80,110,120,130,90,70,6,True

In [45]:
import re

#df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]
df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,False,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,False,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,False,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,False,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,False,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,False,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,False,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,False,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,False,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,False,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,False,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,False,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,False,50,55,50,36,30,43,5,False

In [ ]:
#conditional changes